### ISSUE TITLE
Reduce size of API by using structs

### ISSUE THREAD

**Issue by okmatija** [kujukuju/KodaJai#1]
What do you think of replacing all the get_xxx functions which accept a PixelFormat with a single function get_pixel_format_info which returns a small struct containing everything (stride, component count, gl_format, gl_internal_format, gl_type and flags for stuff like if it's a float or depth format). You could do a similar thing for the get_yyy functions accepting a TextureInterp

I really like your code btw, thanks sharing it!

**Comment by kujukuju** [comment]
Thanks! I think something like that is reasonable. I'd like to split it up into logical chunks. I added this code to the pixel format file but I haven't tested or swapped things over to it yet.

You can now access stride/logic info, gl info, and type info from 3 grouped function calls. (Haven't done texture interp yet.)

I think pixel format needs to change in the future because it's a higher level wrapper around opengl stuff, but it's a wrapper in such a way that it loses information.
